module.exports = [ { id:"overview",
    alias:"Overview",
    type:"category",
    route:"overview",
    items:[ { id:"vision",
        alias:"Vision",
        type:"route",
        route:"overview.vision",
        keywords:[ " Consistency",
          " Community",
          " Convention",
          " Abstraction" ] },
      { id:"roadmap",
        alias:"Roadmap",
        type:"route",
        route:"overview.roadmap",
        keywords:[  ] },
      { id:"defects",
        alias:"Defects",
        type:"route",
        route:"overview.defects",
        keywords:[  ] },
      { id:"changelog",
        alias:"Changelog",
        type:"route",
        route:"overview.changelog",
        keywords:[  ] } ] },
  { id:"development",
    alias:"Development",
    type:"category",
    route:"development",
    items:[ { id:"environment",
        alias:"Environment",
        type:"route",
        route:"development.environment",
        keywords:[ " Mac",
          " Linux",
          " Windows" ] },
      { id:"app",
        alias:"App",
        type:"route",
        route:"development.app",
        keywords:[ " Project structure",
          " Running an existing project",
          " Creating a new project",
          " Testing a project",
          " Deploying a project" ] },
      { id:"addon",
        alias:"Addon",
        type:"route",
        route:"development.addon",
        keywords:[ " Project structure",
          " Addon namespaces",
          " Addon conventions",
          " Running an existing project",
          " Creating an addon project",
          " Testing an addon",
          " Publishing an addon" ] },
      { id:"learning",
        alias:"Learning",
        type:"route",
        route:"development.learning",
        keywords:[ " Community" ] },
      { id:"notes",
        alias:"Notes",
        type:"route",
        route:"development.notes",
        keywords:[ " IDEs" ] } ] },
  { id:"design-strategy",
    alias:"Design Strategy",
    type:"category",
    route:"design-strategy",
    items:[ { id:"usability-myths",
        alias:"Usability Myths",
        type:"route",
        route:"design-strategy.usability-myths",
        keywords:[  ] },
      { id:"branding",
        alias:"Branding",
        type:"route",
        route:"design-strategy.branding",
        keywords:[  ] } ] },
  { id:"design-conventions",
    alias:"Design Conventions",
    type:"category",
    route:"design-conventions",
    items:[ { id:"typography",
        alias:"Typography",
        type:"route",
        route:"design-conventions.typography",
        keywords:[  ] },
      { id:"layout",
        alias:"Layout",
        type:"route",
        route:"design-conventions.layout",
        keywords:[  ] },
      { id:"colors",
        alias:"Colors",
        type:"route",
        route:"design-conventions.colors",
        keywords:[  ] } ] },
  { id:"design-patterns",
    alias:"Design Patterns",
    type:"category",
    route:"design-patterns",
    items:[ { id:"about",
        alias:"About",
        type:"route",
        route:"design-patterns.about",
        keywords:[  ] },
      { id:"application-bar",
        alias:"Application Bar",
        type:"route",
        route:"design-patterns.application-bar",
        keywords:[  ] },
      { id:"date:time-input",
        alias:"Date:time Input",
        type:"route",
        route:"design-patterns.date:time-input",
        keywords:[  ] },
      { id:"error-page",
        alias:"Error Page",
        type:"route",
        route:"design-patterns.error-page",
        keywords:[  ] },
      { id:"filtering",
        alias:"Filtering",
        type:"route",
        route:"design-patterns.filtering",
        keywords:[  ] },
      { id:"forms",
        alias:"Forms",
        type:"category",
        route:"design-patterns.forms",
        items:[ { id:"overview",
            alias:"Overview",
            type:"route",
            route:"design-patterns.forms.overview",
            keywords:[  ],
            items:[ { id:"detail",
                alias:"Detail",
                type:"route",
                route:"design-patterns.forms.overview.detail" },
              { id:"form",
                alias:"Form",
                type:"route",
                route:"design-patterns.forms.overview.form" },
              { id:"detail-update",
                alias:"Detail Update",
                type:"route",
                route:"design-patterns.forms.overview.detail-update" } ] },
          { id:"create",
            alias:"Create",
            type:"route",
            route:"design-patterns.forms.create",
            keywords:[  ] },
          { id:"edit",
            alias:"Edit",
            type:"route",
            route:"design-patterns.forms.edit",
            keywords:[  ] } ] },
      { id:"global-search",
        alias:"Global Search",
        type:"route",
        route:"design-patterns.global-search",
        keywords:[  ] },
      { id:"home-page",
        alias:"Home Page",
        type:"category",
        route:"design-patterns.home-page",
        items:[ { id:"sample-layouts",
            alias:"Sample Layouts",
            type:"route",
            route:"design-patterns.home-page.sample-layouts",
            keywords:[  ] } ] },
      { id:"info-bar",
        alias:"Info Bar",
        type:"route",
        route:"design-patterns.info-bar",
        keywords:[  ] },
      { id:"login-logout",
        alias:"Login Logout",
        type:"route",
        route:"design-patterns.login-logout",
        keywords:[  ] },
      { id:"notifications",
        alias:"Notifications",
        type:"route",
        route:"design-patterns.notifications",
        keywords:[  ] },
      { id:"object-browser",
        alias:"Object Browser",
        type:"category",
        route:"design-patterns.object-browser",
        items:[ { id:"overview",
            alias:"Overview",
            type:"route",
            route:"design-patterns.object-browser.overview",
            keywords:[ " Viewing change details",
              " Freezing contents temporarily" ] },
          { id:"list",
            alias:"List",
            type:"route",
            route:"design-patterns.object-browser.list",
            keywords:[  ] },
          { id:"table",
            alias:"Table",
            type:"route",
            route:"design-patterns.object-browser.table",
            keywords:[  ] } ] },
      { id:"object-details",
        alias:"Object Details",
        type:"route",
        route:"design-patterns.object-details",
        keywords:[  ] },
      { id:"user-feedback",
        alias:"User Feedback",
        type:"category",
        route:"design-patterns.user-feedback",
        items:[ { id:"confirmation-dialog",
            alias:"Confirmation Dialog",
            type:"route",
            route:"design-patterns.user-feedback.confirmation-dialog",
            keywords:[  ] },
          { id:"notifications",
            alias:"Notifications",
            type:"route",
            route:"design-patterns.user-feedback.notifications",
            keywords:[  ] } ] } ] },
  { id:"ui-components",
    alias:"UI Components",
    type:"category",
    route:"ui-components",
    items:[ { id:"button-controls",
        alias:"Button Controls",
        type:"category",
        route:"ui-components.button-controls",
        items:[ { id:"button",
            alias:"Button",
            type:"route",
            route:"ui-components.button-controls.button",
            keywords:[ " **Basic primary button**",
              " **Basic secondary button**",
              " <span style=\"color: rgb(0,0,0);\"><span class=\"inline-comment-marker\" data-ref=\"72a40cba-0d63-465a-8719-e5e661c7b411\">Basic tertiary button</span></span>",
              " **<span style=\"color: rgb(0,0,0);\">Placement of buttons</span>**",
              " Special buttons" ] },
          { id:"link",
            alias:"Link",
            type:"route",
            route:"ui-components.button-controls.link",
            keywords:[  ],
            items:[ { id:"min",
                alias:"First",
                type:"route",
                route:"ui-components.button-controls.link.min" },
              { id:"first",
                alias:"First",
                type:"route",
                route:"ui-components.button-controls.link.min",
                path:{ path:"ui-components/button-controls/link/first/:first_id" },
                items:[ { id:"second",
                    alias:"Second",
                    type:"route",
                    path:{ path:"ui-components/button-controls/link/second/:second_id" },
                    route:"ui-components.button-controls.link.first.second" } ] } ] },
          { id:"checkbox",
            alias:"Checkbox",
            type:"route",
            route:"ui-components.button-controls.checkbox",
            keywords:[  ] },
          { id:"checkbox-group",
            alias:"Checkbox Group",
            type:"route",
            route:"ui-components.button-controls.checkbox-group",
            keywords:[  ] },
          { id:"help-button",
            alias:"Help Button",
            type:"route",
            route:"ui-components.button-controls.help-button",
            keywords:[  ] },
          { id:"radio-button",
            alias:"Radio Button",
            type:"route",
            route:"ui-components.button-controls.radio-button",
            keywords:[  ] },
          { id:"radio-button-group",
            alias:"Radio Button Group",
            type:"route",
            route:"ui-components.button-controls.radio-button-group",
            keywords:[  ] },
          { id:"toggle",
            alias:"Toggle",
            type:"route",
            route:"ui-components.button-controls.toggle",
            keywords:[  ] } ] },
      { id:"menu-controls",
        alias:"Menu Controls",
        type:"category",
        route:"ui-components.menu-controls",
        items:[ { id:"navigation",
            alias:"Navigation",
            type:"route",
            route:"ui-components.menu-controls.navigation",
            keywords:[  ],
            items:[ { id:"resource",
                alias:"Resource",
                type:"route",
                route:"ui-components.menu-controls.navigation.resource" },
              { id:"dashboard",
                alias:"Dashboard",
                type:"route",
                route:"ui-components.menu-controls.navigation.dashboard" } ],
            modals:[ { modalName:"frost-navigation-modal",
                modal:{ withParams:"fiberplantNav",
                  otherParams:{ fiberplantNavTemplate:"navigationTemplate" },
                  dialogClass:"frost-navigation-modal",
                  actions:{ openRoute:"openRoute" } } },
              { modalName:"frost-navigation-modal",
                modal:{ withParams:"adminNav",
                  otherParams:{ fiberplantNavTemplate:"navigationTemplate" },
                  dialogClass:"frost-navigation-modal",
                  actions:{ openRoute:"openRoute" } } } ] },
          { id:"command-menu",
            alias:"Command Menu",
            type:"route",
            route:"ui-components.menu-controls.command-menu",
            keywords:[  ] },
          { id:"context-menu",
            alias:"Context Menu",
            type:"route",
            route:"ui-components.menu-controls.context-menu",
            keywords:[  ] },
          { id:"disclosure-tab",
            alias:"Disclosure Tab",
            type:"route",
            route:"ui-components.menu-controls.disclosure-tab",
            keywords:[  ] } ] },
      { id:"indicator-controls",
        alias:"Indicator Controls",
        type:"category",
        route:"ui-components.indicator-controls",
        items:[ { id:"notifications",
            alias:"Notifications",
            type:"route",
            route:"ui-components.indicator-controls.notifications",
            keywords:[  ] },
          { id:"badges",
            alias:"Badges",
            type:"route",
            route:"ui-components.indicator-controls.badges",
            keywords:[  ] },
          { id:"progress-indicators",
            alias:"Progress Indicators",
            type:"route",
            route:"ui-components.indicator-controls.progress-indicators",
            keywords:[  ] },
          { id:"transient-messages",
            alias:"Transient Messages",
            type:"route",
            route:"ui-components.indicator-controls.transient-messages",
            keywords:[  ] } ] },
      { id:"input-controls",
        alias:"Input Controls",
        type:"category",
        route:"ui-components.input-controls",
        items:[ { id:"text",
            alias:"Text",
            type:"route",
            route:"ui-components.input-controls.text",
            keywords:[ " Simple text field:",
              " Auto-complete text field:",
              " <span style=\"color: rgb(51,51,0);\">Specific auto-complete text field behaviours</span>" ] },
          { id:"text-area",
            alias:"Text Area",
            type:"route",
            route:"ui-components.input-controls.text-area",
            keywords:[  ] },
          { id:"password",
            alias:"Password",
            type:"route",
            route:"ui-components.input-controls.password",
            keywords:[  ] },
          { id:"file-chooser",
            alias:"File Chooser",
            type:"route",
            route:"ui-components.input-controls.file-chooser",
            keywords:[  ] },
          { id:"select",
            alias:"Select",
            type:"route",
            route:"ui-components.input-controls.select",
            keywords:[  ] },
          { id:"slider",
            alias:"Slider",
            type:"route",
            route:"ui-components.input-controls.slider",
            keywords:[  ] },
          { id:"modal-dialog-input",
            alias:"Modal Dialog Input",
            type:"route",
            route:"ui-components.input-controls.modal-dialog-input",
            keywords:[  ],
            modalName:"frost-create-form",
            modal:{ withParams:"showModalForm",
              dialogClass:"frost-bunsen-form-dialog",
              actions:{ save:"save" } } } ] },
      { id:"text",
        alias:"Text",
        type:"category",
        route:"ui-components.text",
        items:[ { id:"tone",
            alias:"Tone",
            type:"route",
            route:"ui-components.text.tone",
            keywords:[  ] },
          { id:"capitalization",
            alias:"Capitalization",
            type:"route",
            route:"ui-components.text.capitalization",
            keywords:[  ] },
          { id:"titles",
            alias:"Titles",
            type:"route",
            route:"ui-components.text.titles",
            keywords:[  ] },
          { id:"labels",
            alias:"Labels",
            type:"route",
            route:"ui-components.text.labels",
            keywords:[  ] },
          { id:"units",
            alias:"Units",
            type:"route",
            route:"ui-components.text.units",
            keywords:[  ] },
          { id:"truncation",
            alias:"Truncation",
            type:"route",
            route:"ui-components.text.truncation",
            keywords:[  ] } ] },
      { id:"content-views",
        alias:"Content Views",
        type:"category",
        route:"ui-components.content-views",
        items:[ { id:"about-dialog",
            alias:"About Dialog",
            type:"route",
            route:"ui-components.content-views.about-dialog",
            keywords:[  ],
            modalName:"frost-about-dialog",
            modal:{ withParams:"isAboutVisible",
              dialogClass:"frost-bunsen-form-dialog",
              otherParams:[ { dialogType:"company" },
                { dialogTitle:"title" },
                { dialogMessage:"message" },
                { dialogServerMessage:"serverMessage" },
                { dialogCopyrightText:"copyrightText" },
                { dialogLicenseText:"licenseText" } ],
              actions:{ save:"dialogConfirmed" } } },
          { id:"accordion",
            alias:"Accordion",
            type:"route",
            route:"ui-components.content-views.accordion",
            keywords:[  ] },
          { id:"collapsible-section",
            alias:"Collapsible Section",
            type:"route",
            route:"ui-components.content-views.collapsible-section",
            keywords:[  ] },
          { id:"info-pods",
            alias:"Info Pods",
            type:"route",
            route:"ui-components.content-views.info-pods",
            keywords:[  ] },
          { id:"list",
            alias:"List",
            type:"route",
            route:"ui-components.content-views.list",
            keywords:[  ] },
          { id:"modal-dialog",
            alias:"Modal Dialog",
            type:"route",
            route:"ui-components.content-views.modal-dialog",
            keywords:[  ] },
          { id:"scrollbar",
            alias:"Scrollbar",
            type:"route",
            route:"ui-components.content-views.scrollbar",
            keywords:[  ] },
          { id:"table",
            alias:"Table",
            type:"route",
            route:"ui-components.content-views.table",
            keywords:[  ] },
          { id:"tabs",
            alias:"Tabs",
            type:"route",
            route:"ui-components.content-views.tabs",
            keywords:[  ] },
          { id:"info-bar",
            alias:"Info Bar",
            type:"route",
            route:"ui-components.content-views.info-bar",
            keywords:[  ] },
          { id:"sort",
            alias:"Sort",
            type:"route",
            route:"ui-components.content-views.sort",
            keywords:[  ] } ] },
      { id:"icons",
        alias:"Icons",
        type:"route",
        route:"ui-components.icons",
        keywords:[  ] } ] },
  { id:"contributing",
    alias:"Contributing",
    type:"category",
    route:"contributing",
    items:[ { id:"frost-guide",
        alias:"Frost Guide",
        type:"route",
        route:"contributing.frost-guide",
        keywords:[ " Editing an Existing Page",
          " Adding a New Page",
          " Editing Scrollspy Tabs",
          " Creating Component Pages",
          " Updating Component Pages",
          " Adding images" ] },
      { id:"contributors",
        alias:"Contributors",
        type:"route",
        route:"contributing.contributors.contributors" },
      { id:"contributor",
        alias:"Contributor",
        type:"route",
        route:"contributing.contributors.contributor" } ] } ]
